#port-server
server:
  port: 8088
  address: 0.0.0.0

spring:
  datasource:
    url: jdbc:mysql://root:EFOfAfDlNsnMybszRdaNAcVlMpOeLbQT@metro.proxy.rlwy.net:49755/railway
    username: root
    password: EFOfAfDlNsnMybszRdaNAcVlMpOeLbQT
    driver-class-name: com.mysql.cj.jdbc.Driver
#    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false # Hiển thị câu SQL trong console
    hibernate:
      ddl-auto: none # Tùy chọn: validate, update, create, create-drop #de none de khong cap ngat database
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      format-sql: true # Định dạng câu SQL đẹp hơn
  #redis
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
  #image
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  #login-other
  security:
    oauth2:
      client:
        registration:
          #login-gg
          google:
            client-id: 903939132080-8f1s8o9fgb80q8est4j8he4hhr86rjhd.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "${GOOGLE_REDIRECT_URI:http://localhost:4200/auth/google/callback}"
            auth-uri: https://accounts.google.com/o/oauth2/v2/auth
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            scope: profile,email
            resource-server:
              opaque-token:
                introspection-uri: "https://googleapis.com"
          #login-fb
          facebook:
            client-id: 679621127764992
            client-secret: a54c2fa9035b4087a7bffd2ce7d8311f
            redirect-uri: "${FACEBOOK_REDIRECT_URI:http://localhost:4200/auth/facebook/callback}"
            auth-uri: https://www.facebook.com/v22.0/dialog/oauth
            token-uri: https://graph.facebook.com/oauth/access_token?grant_type=authorization_code
            user-info-uri: https://graph.facebook.com/me?fields=id,name,email,picture.type(large)
            scope:
              - public_profile
              - email

  #mail-forgot-password
  mail:
    host: smtp.gmail.com
    port: 587
    username: tu123098b@gmail.com
    password: ylzgsbsjndyzvnlo
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
#api
api:
  prefix: /api/v1

#cloudinary
cloudinary:
  cloudName: dyzdqrbw8
  apiKey: 757177834276449
  apiSecret: qPik8swLit-zRJhjffcIdFSVMfQ

#json web token
jwt:
  expiration: 2592000 #30days: 30*24*60*60
  secretKey: FfyEJyyYieuIdNN99gm8ibEik38pjPBk7elv2qz4utE=

logging:
  level:
    org.springframework.security: DEBUG #deloy -> off

# swagger-ui custom path
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
  show-actuator: true

# health check
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /api/v1/actuator
      exposure:
        #include: "health"
        include: health, info
google:
  recaptcha:
    secret: 6LeoEisrAAAAJB6N1RKL5PE3CVwFRlN4HyT2Tzg
#6LeoEisrAAAAADZ06P_twZz1lTK55Wz8Zg6kIZdD
