server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/itwork?useSSL=false&serverTimezone=UTC
    username: root
    password: an147258
    driver-class-name: com.mysql.cj.jdbc.Driver
#    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true # Hiển thị câu SQL trong console
    hibernate:
      ddl-auto: none # Tùy chọn: validate, update, create, create-drop #de none de khong cap ngat database
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      format-sql: true # Định dạng câu SQL đẹp hơn
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
api:
  prefix: api/v1
cloudinary:
  cloudName: dyzdqrbw8
  apiKey: 757177834276449
  apiSecret: qPik8swLit-zRJhjffcIdFSVMfQ
jwt: #json web token
  expiration: 2592000 #30days: 30*24*60*60
  secretKey: FfyEJyyYieuIdNN99gm8ibEik38pjPBk7elv2qz4utE=
