services:
  database:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: <root_password>
      MYSQL_DATABASE: <database_name>
      MYSQL_USER: <user_name>
      MYSQL_PASSWORD: <user_password>
    ports:
      - 3306:3306
volumes:
  mysql: